#!/usr/bin/env python3
"""
Remove generated/junk output from multiphysics_amr run directories so they
can be resubmitted cleanly.

A "run directory" is any directory containing multiphysics_amr.sh (e.g.
3x3_uniform_all_over/0th, 17x17_rodded/0th, ...). Input files (*.i, *.sh),
model.xml, pincenters.txt, power_profile.txt and anything else not on the
junk list below are never touched. Case-level mesh files one level up
(mesh_neutronics_in.e, mesh_hc_in.e) are also untouched -- only files
inside a run directory itself are candidates.

Usage:
  python garbage_clean.py                       # dry run, everything under root
  python garbage_clean.py --yes                  # actually delete, everything
  python garbage_clean.py 3x3_uniform_all_over    # dry run, one case (all its run dirs)
  python garbage_clean.py 3x3_uniform_all_over/2nd --yes   # actually delete, one run dir
  python garbage_clean.py 2nd --yes               # actually delete every run dir named "2nd" in any case
  python garbage_clean.py --list                  # just show detected run dirs, no cleaning
"""

import argparse
import fnmatch
import os
import shutil
import sys
from pathlib import Path

# Files (glob patterns, matched against the file's own name) that are safe
# to delete from a run directory -- all of these are regenerated by
# multiphysics_amr.sh on the next submission.
JUNK_FILE_GLOBS = [
    "openmc_mesh_in.e",
    "openmc_out.e",
    "openmc_out.csv",
    "openmc_out_solid0.e",
    "openmc_out_solid0.csv",
    "openmc_out_sub_channel0.e",
    "subchannel_detailed.e",
    "subchannel_detailed.csv",
    "summary.h5",
    "tallies.out",
    "statepoint.*.h5",
    "*.[0-9]*.out",   # slurm stdout, e.g. base_case.1160970.out
    "*.[0-9]*.err",   # slurm stderr, e.g. base_case.1160970.err
]

# Directories (matched against the dir's own name) that are safe to remove
# entirely.
JUNK_DIR_NAMES = [
    "openmc_out_cp",
    ".jitcache",
    ".vscode",
]

MARKER_FILE = "multiphysics_amr.sh"


def human_size(num_bytes):
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if num_bytes < 1024:
            return f"{num_bytes:.1f}{unit}"
        num_bytes /= 1024
    return f"{num_bytes:.1f}PB"


def dir_size(path):
    total = 0
    for dirpath, _, filenames in os.walk(path):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            if os.path.exists(fp):
                total += os.path.getsize(fp)
    return total


def find_run_dirs(root):
    """Any directory containing multiphysics_amr.sh, sorted for stable output."""
    run_dirs = []
    for dirpath, _, filenames in os.walk(root):
        if MARKER_FILE in filenames:
            run_dirs.append(Path(dirpath))
    return sorted(run_dirs)


def matches_target(run_dir, root, targets):
    """True if run_dir should be included given the user-supplied target list."""
    if not targets:
        return True
    rel = run_dir.relative_to(root).as_posix()
    name = run_dir.name
    for t in targets:
        t = t.rstrip("/")
        if t == name or t == rel:
            return True
        if rel.startswith(t + "/"):
            return True
    return False


def junk_in(run_dir):
    """Yield (path, is_dir, size_bytes) for junk found directly inside run_dir."""
    for entry in sorted(run_dir.iterdir()):
        if entry.is_dir():
            if entry.name in JUNK_DIR_NAMES:
                yield entry, True, dir_size(entry)
        else:
            if any(fnmatch.fnmatch(entry.name, pat) for pat in JUNK_FILE_GLOBS):
                yield entry, False, entry.stat().st_size


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("targets", nargs="*", help="case and/or run-dir names/paths to restrict to (default: all)")
    parser.add_argument("--root", default=str(Path(__file__).resolve().parent), help="hpc_debug root to search (default: this script's directory)")
    parser.add_argument("--yes", action="store_true", help="actually delete (default is a dry run)")
    parser.add_argument("--list", action="store_true", help="just list detected run directories and exit")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    run_dirs = find_run_dirs(root)

    if args.list:
        for rd in run_dirs:
            print(rd.relative_to(root))
        return

    selected = [rd for rd in run_dirs if matches_target(rd, root, args.targets)]
    if not selected:
        print("No run directories matched.", file=sys.stderr)
        sys.exit(1)

    grand_total = 0
    for rd in selected:
        items = list(junk_in(rd))
        if not items:
            continue
        subtotal = sum(size for _, _, size in items)
        grand_total += subtotal
        print(f"\n{rd.relative_to(root)}  ({human_size(subtotal)})")
        for path, is_dir, size in items:
            kind = "dir " if is_dir else "file"
            print(f"  [{kind}] {path.name:35s} {human_size(size):>10s}")
            if args.yes:
                if is_dir:
                    shutil.rmtree(path)
                else:
                    path.unlink()

    print(f"\n{'Removed' if args.yes else 'Would remove'} {human_size(grand_total)} total across {len(selected)} run directories.")
    if not args.yes:
        print("Dry run only -- re-run with --yes to actually delete.")


if __name__ == "__main__":
    main()
